namespace ModGenerator.Helpers;

public static class NumberToText
{
    private static readonly Dictionary<int, string> Lookup = new()
    {
        {0, "None"},
        {1, "One"},
        {2, "Two"},
        {3, "Three"},
        {4, "Four"},
        {5, "Five"},
        {6, "Six"},
        {7, "Seven"},
        {8, "Eight"},
        {9, "Nine"},
        {10, "Ten"},
        {11, "Eleven"},
        {12, "Twelve"},
        {13, "Thirteen"},
        {14, "Fourteen"},
        {15, "Fifteen"},
        {16, "Sixteen"},
        {17, "Seventeen"},
        {18, "Eighteen"},
        {19, "Nineteen"},
        {20, "Twenty"},
        {21, "TwentyOne"},
        {22, "TwentyTwo"},
        {23, "TwentyThree"},
        {24, "TwentyFour"},
        {25, "TwentyFive"},
        {26, "TwentySix"},
        {27, "TwentySeven"},
        {28, "TwentyEight"},
        {29, "TwentyNine"},
        {30, "Thirty"},
        {31, "ThirtyOne"},
        {32, "ThirtyTwo"},
        {33, "ThirtyThree"},
        {34, "ThirtyFour"},
        {35, "ThirtyFive"},
        {36, "ThirtySix"},
        {37, "ThirtySeven"},
        {38, "ThirtyEight"},
        {39, "ThirtyNine"},
        {40, "Forty"},
        {41, "FortyOne"},
        {42, "FortyTwo"},
        {43, "FortyThree"},
        {44, "FortyFour"},
        {45, "FortyFive"},
        {46, "FortySix"},
        {47, "FortySeven"},
        {48, "FortyEight"},
        {49, "FortyNine"},
        {50, "Fifty"}
    };

    public static string Convert(int number) => Lookup.GetValueOrDefault(number) ?? string.Empty;
}
